apiVersion: v2
name: webank
description: A Helm chart for Kubernetes

type: application

version: 1.0.2-rc.2

appVersion: "1.16.0"

dependencies:
  - name: webank-obs
    repository: "file://../webank-obs/"
    version: 1.0.2-rc
    alias: obs
  - name: webank-userapp
    repository: "file://../webank-userapp/"
    version: 1.0.1
    alias: userapp
  - name: postgresql
    repository: "https://repo.broadcom.com/bitnami-files/"
    version: 16.2.3
    alias: db
    condition: db.enabled
  - name: common
    version: 2.27.0
    repository: "https://repo.broadcom.com/bitnami-files/"