apiVersion: v2
name: webank
description: A Helm chart for Kubernetes

type: application

version: 1.0.0-rc

appVersion: "1.16.0"

dependencies:
  - name: webank-obs
    repository: "https://ADORSYS-GIS.github.io/webank-devops/"
    version: 0.1.0
    alias: obs
  - name: webank-userapp
    repository: "https://ADORSYS-GIS.github.io/webank-devops/"
    version: 0.1.0
    alias: userapp
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: 16.2.3
    alias: db
    condition: db.enabled
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami