apiVersion: v2
name: webank
description: A Helm chart for Kubernetes

type: application

version: 1.3.0-rc-1

appVersion: "1.16.0"

dependencies:
  - name: webank-obs
    repository: "https://ADORSYS-GIS.github.io/webank-devops/"
    version: 1.2.0
    alias: obs
  - name: webank-userapp
    repository: "https://ADORSYS-GIS.github.io/webank-devops/"
    version: 1.0.1
    alias: userapp
  - name: webank-prs
    repository: "https://ADORSYS-GIS.github.io/webank-devops/"
    version: 1.0.1-rc
    alias: prs
  - name: postgresql
    repository: "https://repo.broadcom.com/bitnami-files/"
    version: 16.2.3
    alias: db
    condition: db.enabled
  - name: common
    version: 2.27.0
    repository: "https://repo.broadcom.com/bitnami-files/"