apiVersion: v2
name: webank
description: A Helm chart for webank

type: application

version: 0.1.0
appVersion: "1.16.0"


dependencies:
  - name: webank-obs
    repository: "file://../webank-obs"
    version: 0.1.0
    alias: obs
  - name: webank-userapp
    repository: "file://../webank-userapp"
    version: 0.1.0
    alias: userapp