obs:
  service:
    type: ClusterIP
  ingress:
    enabled: false

userapp:
  service:
    type: ClusterIP
  ingress:
    enabled: false

db:
  primary:
    service:
      type: ClusterIP
      port: 5432
    replicaCount: 2   
  auth:
    postgresPassword: "admin-password"
    username: "webank-user"
    password: "user-password"
    database: "webank-db"  
  metrics:
    enabled: true