global:
  postgresql:
    auth:
      postgresPassword: "admin-password"
      username: "selast-user"
      password: "selast-password"
      database: "selast-db"

obs:
  database:
    host: "{{ .Release.Name }}-postgresql"
    name: "{{ .Values.global.postgresql.auth.database }}"
    user: "{{ .Values.global.postgresql.auth.username }}"
    password: "{{ .Values.global.postgresql.auth.password }}"

db:
  enabled: true
  primary:
    service:
      type: ClusterIP
      port: 5432
    replicaCount: 2
  metrics:
    enabled: true