apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webank
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://adorsys-gis.github.io/webank-devops
    chart: webank
    targetRevision: 1.2.0-rc.2
    helm:
      releaseName: webank
      valueFiles:
        - values.yaml
      valuesObject:
        db:
          enabled: false
        userapp:
          image:
            tag: de9b5d4807fe7e002082f31206853e0532900a9f
            pullPolicy: Always
          env:
            - name: VITE_WEBANK_OBS_URL
              value: '/api'
            - name: VITE_WEBANK_PRS_URL
              value: '/api/prs'
          envFrom:
          - secretRef:
              name: webank_userapp_secret
        
        obs:
          image:
            tag: 78c51e02b81dd2bb881a978368a859f7a6ba047e
            pullPolicy: Always
          env: 
          - name: SPRING_PROFILES_ACTIVE
            value: postgres
          envFrom:
          - secretRef:
              name: webank-obs-secret
           
          database:
            host: webank-dev-env-db.cp4v71vs2xe2.eu-central-1.rds.amazonaws.com
            name: webank_dev_env
            user: webank
            secretName: rds-secret

        prs:
          image:
            tag: 4068a65d8c5ead153fd94f72b317a89a5b69475b
            pullPolicy: Always
          env: 
          - name: SPRING_PROFILES_ACTIVE
            value: postgres
          envFrom:
          - secretRef:
              name: webank-prs-secret

          database:
            host: webank-dev-env-db.cp4v71vs2xe2.eu-central-1.rds.amazonaws.com
            name: webank_dev_env
            user: webank
            secretName: rds-secret
          
        ingress:
          host: dev.webank.gis.ssegning.com
          className: alb
          annotations:
            alb.ingress.kubernetes.io/tags: Environment=dev,Owner=webank
            alb.ingress.kubernetes.io/load-balancer-name: webank-dev
            alb.ingress.kubernetes.io/listen-ports: |
              [
                {
                  "HTTP":80
                }, 
                {
                  "HTTPS": 443
                }
              ]
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
            alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/1cee4019-ba69-40a8-a888-95f62a376f88"
            external-dns.alpha.kubernetes.io/hostname: "dev.webank.gis.ssegning.com"
            alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
            alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
            alb.ingress.kubernetes.io/healthy-threshold-count: '2'
            alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  destination:
    server: https://kubernetes.default.svc
    namespace: webank
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    revisionHistoryLimit: 4