vpc_cidr                   = "12.34.0.0/16"
name                       = "dev-cluster"
db_username                = "admin"
environment                = "dev"
eks_min_instance           = 1
eks_max_instance           = 3
eks_desired_instance       = 2
db_backup_retention_period = null
db_skip_final_snapshot     = true
zone_name                  = "dev.webank.gis.ssegning.com"
eks_ec2_instance_types = ["t2.nano", "t2.medium", "t2.large"]