region                     = "eu-west-1"
vpc_cidr                   = "12.34.0.0/16"
db_username                = "admin"
environment                = "dev"
eks_min_instance           = 1
eks_max_instance           = 3
eks_desired_instance       = 2
db_backup_retention_period = null
db_skip_final_snapshot     = true
azs = ["eu-west-1a", "eu-west-1b"]
eks_ec2_instance_types = ["t2.medium"]