{{- if not .Values.Database.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-db-secret
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.Database.user | b64enc | quote }}
  password: {{ .Values.Database.password | b64enc | quote }}
{{- end }}