apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webank-monitoring.fullname" . }}-grafana-config
  labels:
    app: grafana
data:
  grafana.ini: |
    [security]
    admin_user = {{ .Values.grafana.admin.user }}
    admin_password = {{ .Values.grafana.admin.password }}

    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/default.json

    [paths]
    provisioning = /etc/grafana/provisioning
