apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager:{{ .Values.alertmanager.service.port }}"

    scrape_configs:
      - job_name: 'webank-obs-backend'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['dev.webank.gis.ssegning.com/api']
      - job_name: 'webank-prs-backend'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['dev.webank.gis.ssegning.com/api/prs']

    # Adding alerting rules here
    rule_files:
      - /etc/prometheus/rules/prometheus.rules.yml
