app:
  name: webank-obs

replicaCount: 1

image:
  repository: ghcr.io/adorsys-gis/webank-online-banking
  tag: 1.2.3

service:
  type: ClusterIP
  port: 8080

database:
  name: "{{ .Values.app.name }}-db"
  host: webank-db
  port: 5432
  user: webank-user
  password: webank-password
  secretName: ~
  secretKey: password

springBoot:
  profiles: prod