## @param kubeVersion Override Kubernetes version
##
kubeVersion: ~
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: ~
## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: ~
## @param commonLabels Labels to add to all deployed resources
##
commonLabels: ~
## @param commonAnnotations Annotations to add to all deployed resources
##
commonAnnotations: ~

## @param replicaCount Number of replicas to deploy
##
replicaCount: 1

## @param strategy Deployment strategy
##
strategy:
  ## @param type Type of deployment strategy
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  type: RollingUpdate
  ## @param rollingUpdate Rolling update configuration
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment
  rollingUpdate:
    ## @param maxUnavailable The maximum number of pods that can be unavailable during the update process
    ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    maxUnavailable: 25%
    ## @param maxSurge The maximum number of pods that can be scheduled above the desired number of pods
    ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    maxSurge: 25%

autoscaling:
  ## @param enabled Enable autoscaling
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  enabled: false
  ## @param minReplicas Minimum number of replicas
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  minReplicas: 1
  ## @param maxReplicas Maximum number of replicas
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  maxReplicas: 3
  ## @param targetCPUUtilizationPercentage Target CPU utilization percentage
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  targetCPUUtilizationPercentage: 50
  ## @param targetMemoryUtilizationPercentage Target memory utilization percentage
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  targetMemoryUtilizationPercentage: 50

resources:
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  requests:
    ## CPU resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits
    cpu: 200m
    ## Memory resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits
    memory: 512Mi
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  limits:
    ## CPU resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits
    cpu: 400m
    ## Memory resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits
    memory: 1Gi

## @param podDisruptionBudget PodDisruptionBudget configuration
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
volumes: [ ]

## @param podDisruptionBudget PodDisruptionBudget configuration
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
volumeMounts: [ ]

## @param podDisruptionBudget PodDisruptionBudget configuration
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

## @param podDisruptionBudget PodDisruptionBudget configuration
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
envFrom: [ ]

##
##
image:
  ## Specify a Registry for the image
  ## ref: https://kubernetes.io/docs/concepts/containers/images
  registry: ghcr.io
  ## Specify a Repository for the image
  ## ref: https://kubernetes.io/docs/concepts/containers/images
  repository: adorsys-gis/webank-online-banking
  ## Specify a Tag for the image
  ## ref: https://kubernetes.io/docs/concepts/containers/images
  tag: 'latest'
  ## Specify a digest for the image
  ## ref: https://kubernetes.io/docs/concepts/containers/images
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - name: myRegistryKeySecretName
  ##
  pullSecrets: []


## Liveness probe values
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

## Readiness probe values
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

## @param service Kubernetes service configuration
##
service:
  ## Kubernetes service additional labels
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  additionalLabels: "{{ $.Values.commonLabels | toYaml }}"
  ## Kubernetes service type
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  ## Kubernetes service port
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
  port: 8080
  ## Kubernetes service targetPort
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
  targetPort: 8080
  ## Kubernetes annotations for service
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
  annotations: "{{ $.Values.commonAnnotations | toYaml }}"
  ## LoadBalancerIP if service type is LoadBalancer
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  loadBalancerIP: ~
  ## LoadBalancer sourceRanges if service type is LoadBalancer
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  allocateLoadBalancerNodePorts: ~
  ## ClusterIP if service type is ClusterIP
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#clusterip
  clusterIP: null

serviceAccount:
  ## Specifies whether a service account should be created
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  create: false

  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  automount: true

ingress:
  ## Additional labels for Ingress
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  additionalLabels: "{{ $.Values.commonLabels | toYaml }}"
  ## Enable Ingress
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  enabled: true
  ## Ingress classname
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
  className: ""
  ## Ingress annotations
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
  annotations: "{{ $.Values.commonAnnotations | toYaml }}"
  ## Ingress hostnames
  ## Must be provided if Ingress is enabled
  host: '{{ include "common.names.fullname" $ }}.webank.local'
  ## Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  tls: false

## @param persistence Persistence configuration
##
database:
  ##
  ##
  name: '{{ template "common.names.fullname" . }}-db'
  ##
  ##
  host: webank-db
  ##
  ##
  port: 5432
  ##
  ##
  user: webank-user
  ##
  ##
  password: webank-password
  ##
  ##
  secretName: ~
  ##
  ##
  secretKey: password