app:
  name: webank-obs
replicaCount: 2

image:
  repository: ghcr.io/adorsys-gis/webank-online-banking
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

imagePullSecrets:
  name: ghcr-secret

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
