app:
  name: webank-obs

replicaCount: 2

image:
  repository: ghcr.io/adorsys-gis/webank-online-banking
  tag: latest

service:
  type: LoadBalancer
  port: 8080

imagePullSecrets:
  name: ghcr-secret