{{- if .Values.flyway.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: webank-prs-flyway-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: flyway
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag }}"
          command: ["flyway", "migrate"]
          env:
            - name: FLYWAY_URL
              value: "{{ include "constant.db.url" . }}"
            - name: FLYWAY_USER
              value: "{{ .Values.database.user }}"
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
{{- end }} 