{{ if not .Values.database.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secret.name" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- with include "common.annotations.standard" ( dict "customAnnotations" $.Values.commonAnnotations "context" $ ) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: kubernetes.io/opaque
data:
  username: {{ include "common.tplvalues.render" (dict "value" .Values.database.user "context" $) | b64enc | quote }}
  password: {{ include "common.tplvalues.render" (dict "value" .Values.database.password "context" $) | b64enc | quote }}
{{ end }}