apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.hostName | default "dev.webank.local" }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.userapp.service.name | default "webank-userapp" }} 
                port:
                  number: {{ .Values.userapp.service.port | default 80 }} 
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.obs.service.name | default "webank-obs" }} 
                port:
                  number: {{ .Values.obs.service.port | default 8080 }} 
