apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.hostName }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.userapp.service.name }} 
                port:
                  number: {{ .Values.userapp.service.port }} 
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.obs.service.name }} 
                port:
                  number: {{ .Values.obs.service.port }} 
