{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  {{- with include "common.annotations.standard" ( dict "customAnnotations" $.Values.commonAnnotations "context" $ ) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}