apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          # env:
          #   - name: SERVER_SERVLET_CONTEXTPATH
          #     value: /api
          env:
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "{{ .Values.h2.enabled | quote }}"
            - name: SPRING_H2_CONSOLE_PATH
              value: "{{ .Values.h2.consolePath }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.h2.datasource.url }}"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "{{ .Values.h2.datasource.driverClassName }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.h2.datasource.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.h2.datasource.password }}"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "{{ .Values.h2.ddlAuto }}"
          ports:
            - containerPort: 8080
     
