apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ include "constant.db.url" $ }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ include "common.tplvalues.render" (dict "value" .Values.database.user "context" $) }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ include "db.secret.name" $ }}'
                  key: {{ .Values.database.secretKey }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ include "common.tplvalues.render" (dict "value" .Values.springBoot.profiles "context" $) }}
          ports:
            - containerPort: 8080