{{- if .Values.autoscaling.enabled }}
{{- with .Values.autoscaling -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  {{- with include "common.annotations.standard" ( dict "customAnnotations" $.Values.commonAnnotations "context" $ ) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.names.fullname" $ }}

  {{ with .minReplicas -}}
  minReplicas: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{- end }}

  {{ with .maxReplicas -}}
  maxReplicas: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{- end }}

  metrics:
    {{- if .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ include "common.tplvalues.render" (dict "value" .targetCPUUtilizationPercentage "context" $) }}
    {{- end }}
    {{- if .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ include "common.tplvalues.render" (dict "value" .targetMemoryUtilizationPercentage "context" $) }}
    {{- end }}
{{- end -}}
{{- end -}}