name: Release Charts

on:
  push:
    branches:
      - main
      - fix-for-versioning

jobs:
  webank-deps:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Release Charts ${{ matrix.name }}
    strategy:
      matrix:
        chart:
          - webank-obs
          - webank-userapp
        include:
          - chart: webank-obs
            name: Online Banking Service
          - chart: webank-userapp
            name: User Application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add repos to Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: charts/${{ matrix.chart }}
          skip_existing: true

  webank-main:
    needs:
      - webank-deps
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add repos to Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add webank https://ADORSYS-GIS.github.io/webank-devops
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: charts/webank
          skip_existing: true